### ISSUE TITLE
请教一下我想把数据库改成postgresql，都需要修改哪些地方谢谢

### ISSUE THREAD

**Issue by guduxingzou** [Eternityyyy/Novel#5]
请教一下我想把数据库改成postgresql，都需要修改哪些地方谢谢

**Comment by Eternityyyy** [comment]
需要安装支持postgresql的库，并且修改setting中databases的配置

**Comment by guduxingzou** [comment]
好的 谢谢！另外一个问题咨询一下：book-read.html
	{{chapter.Chapter_text|safe|linebreaksbr}}  这一句怎么改成<p>,因为<br>把所有的空格都删除了，段前空格也丢失了。
以下全部片段。  谢谢！！！
<div class="read-content">
			{% load myfilter %}
			{% if chapter.Chapter_pub and chapter.Chapter_price <= 0 %}
			{{chapter.Chapter_text|safe|linebreaksbr}}
			{% elif chapter.Chapter_pub is False %}
				<p>章节修改中</p>
			{% elif 'uid' in request.session %}
				{% if chapter.buy_user|is_buy_user:request.session.uid %}
				{{chapter.Chapter_text|safe|linebreaksbr}}
				{% else %}
				<p>本章为付费章节</p>
				<p>您当钱余额为：<i>{{request.session.uid|gold}}</i>金币 / 本章需要<i>{{chapter.Chapter_price}}</i>金币</p>
					{% if chapter.Chapter_price <= request.session.uid|gold %}
					<p><a href="/{{chapter.id}}/pay_chapter/">购买本章</a></p>
					{% else %}
					<p><a href="/pay/" target="_blank">前往充值</a></p>
					{% endif %}
				{% endif %}
			{% else %}
			<p><a href="/login/">登录购买</a></p>
			{% endif %}

**Comment by Eternityyyy** [comment]
![image](https://user-images.githubusercontent.com/37318799/98207282-6968a600-1f76-11eb-83fa-e7e2ef662c9c.png)？？？

**Comment by guduxingzou** [comment]
好的 谢谢！另外一个问题咨询一下：book-read.html
{{chapter.Chapter_text|safe|linebreaksbr}} 这一句怎么改成《p》《/p》

,因为《br》《/br》把空格都删除了。  这个编辑器居然也是会识别html代码的！！！

**Comment by Eternityyyy** [comment]
你可以将linebreaksbr改成linebreaks试下

**Comment by guduxingzou** [comment]
好的 谢谢！
